# This workflow will upload a Nuget Package, whenver a tag is created in the form v*

on:
  push:
    tags:
      - v**

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Build WebChannel.Net
      run: |
        dotnet build src
        dotnet pack src --output nupkg
    - name: Test the Package locally
      run: dotnet build examples/chatclient --source nupkg
    # - name: Upload the package to Nuget
    #   run: dotnet nuget push "nupkg/*.nupkg" --api-key {{ secrets.NUGET_SECRET }} --source https://api.nuget.org/v3/index.json